name: CI Build & Release

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          py -m pip install --upgrade pip
          py -m pip install --no-warn-script-location -r requirements.txt pyinstaller pyside6 pyyaml

      - name: Install NSIS
        run: choco install nsis --no-progress --fail-on-standard-error

      - name: Build EXE & Installer
        run: .\build.bat

      - name: Verify Installer Exists
        run: |
          if exist installer.exe (
            echo Moving installer.exe to build folder...
            move /Y installer.exe build\OnTrack_Installer.exe
          )
          if not exist build\OnTrack_Installer.exe (
            echo ERROR: Installer was not generated!
            exit /b 1
          )

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OnTrack-Packages
          path: |
            dist/OnTrack.exe
            build/OnTrack_Installer.exe

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/OnTrack.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Installer to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/OnTrack_Installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
