name: CI Build & Release

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller pyside6 pyyaml

      - name: Install NSIS
        shell: cmd
        run: choco install nsis --no-progress --fail-on-standard-error

      - name: Build EXE & Installer
        shell: cmd
        run: .\build.bat

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OnTrack-Packages
          path: |
            dist/OnTrack.exe
            build/OnTrack_Installer.exe

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/OnTrack.exe
          asset_name: OnTrack.exe
          asset_content_type: application/octet-stream

      - name: Upload Installer to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/OnTrack_Installer.exe
          asset_name: OnTrack_Installer.exe
          asset_content_type: application/octet-stream
